-- AlterTable: Add specific status code columns
ALTER TABLE "Audit" ADD COLUMN "pages_301_permanent" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Audit" ADD COLUMN "pages_302_temporary" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Audit" ADD COLUMN "pages_303_see_other" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Audit" ADD COLUMN "pages_307_temporary" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Audit" ADD COLUMN "pages_308_permanent" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Audit" ADD COLUMN "pages_3xx_other" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Audit" ADD COLUMN "pages_401_unauthorized" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Audit" ADD COLUMN "pages_403_forbidden" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Audit" ADD COLUMN "pages_404_not_found" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Audit" ADD COLUMN "pages_405_method_not_allowed" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Audit" ADD COLUMN "pages_408_timeout" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Audit" ADD COLUMN "pages_410_gone" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Audit" ADD COLUMN "pages_429_rate_limited" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Audit" ADD COLUMN "pages_4xx_other" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Audit" ADD COLUMN "pages_500_internal_error" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Audit" ADD COLUMN "pages_502_bad_gateway" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Audit" ADD COLUMN "pages_503_unavailable" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Audit" ADD COLUMN "pages_504_timeout" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Audit" ADD COLUMN "pages_5xx_other" INTEGER NOT NULL DEFAULT 0;

-- DropForeignKey
ALTER TABLE "public"."Audit" DROP CONSTRAINT "Audit_clientId_fkey";

-- DropForeignKey
ALTER TABLE "public"."Audit" DROP CONSTRAINT "Audit_crawlId_fkey";

-- AddForeignKey
ALTER TABLE "Audit" ADD CONSTRAINT "Audit_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Audit" ADD CONSTRAINT "Audit_crawlId_fkey" FOREIGN KEY ("crawlId") REFERENCES "Crawl"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
