-- AlterTable
ALTER TABLE "Audit" ADD COLUMN     "pages_hreflang_broken_links" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "pages_hreflang_missing_return_tag" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "pages_hreflang_missing_self_ref" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "pages_missing_hreflang_x_default" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "pages_orphaned" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "pages_with_broken_internal_links" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "pages_with_hreflang" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "pages_with_redirect_links" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "total_broken_internal_links" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "total_hreflang_broken_links" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "total_hreflang_links" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "total_hreflang_missing_return_tags" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "total_orphaned_pages" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "total_redirect_internal_links" INTEGER NOT NULL DEFAULT 0;
